install: composer install --prefer-source --dev
language: php
php:
- 5.4
- 5.5
- 5.6
script:
- vendor/bin/phpunit test/
- vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/Currency/
- php vendor/bin/coveralls
