install: composer install --prefer-source --dev
language: php
php:
- 5.6
script:
- vendor/bin/phpunit --coverage-clover clover.xml test/
- vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/Currency/
- php vendor/bin/coveralls
